- name: Bootstrap Ubuntu web host
  hosts: web
  become: true
  vars:
    create_user: "devops"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name:
          - docker.io
          - nginx
        state: present

    - name: Ensure docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create user
      user:
        name: "{{ create_user }}"
        groups: docker
        append: yes
        shell: /bin/bash

    - name: Simple index
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Provisioned by Ansible</h1>"
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Ensure nginx
      service:
        name: nginx
        state: started
        enabled: yes
